# Site settings
title: Engineered Intelligen(ce|t) Engineering
email: actsasgeek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog in the fuzzy intersection of software engineering, artificial intelligence and data-science.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://actsasgeek.github.io" # the base hostname & protocol for your site
twitter_username: acts_as_geek
github_username:  actsasgeek

# Build settings
markdown: kramdown
highlighter: pygments
